name: Release - Verify
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - alpha/*/*
      - release/*/*
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  try:
    uses: kungfu-systems/workflows/.github/workflows/.release-verify.yml@dev/v2/v2.0
    with:
      prebuild: false
      find-dependencies: false
      build-container-enabled: false
      setup-python-enabled: false
      publish-versioning: false
      publish-aws-ci: false
      publish-aws-user: false
      action-bump-version-ref: dev/v4/v4.0
    secrets:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      NODE_AUTH_TOKEN: ${{ secrets.KUNGFU_GITHUB_TOKEN }}

  verify:
    needs: try
    runs-on: ubuntu-24.04
    steps:
      - name: report
        run: echo verified
